name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
